// Prints "name size" for every on-disk type in file_struct_list.inc (types the client reads from or
// writes to files as raw bytes: ReadBuffer/WriteBuffer(sizeof(T)), basestream >> std::vector<T>,
// fread/fwrite, memcpy out of property blobs). Generated by port/scripts/gen_file_struct_sizes.py.
// Built two ways:
//   Windows x86 / MSVC (CI, .github/workflows/build.yml) -> golden file_sizes_win32.txt
//   macOS / clang     (port/scripts/check-file-struct-sizes.sh) -> compared against the golden file
//
// Many of these types are private/protected nested types (DxEffectNeon::OBJECT, ...). They are
// measured through an explicit instantiation, where access checking does not apply to the template
// arguments ([temp.explicit]), so no game header has to change and the layout is not touched.
#include "../../../[Lib]__RanClient/framework.h"
#include "file_struct_headers.inc"
#include <cstdio>
#include <map>
#include <string>

namespace ran_fsize
{
    inline std::map<std::string, unsigned>& table()
    {
        static std::map<std::string, unsigned> t;
        return t;
    }
    inline int record(const char* name, unsigned size)
    {
        table()[name] = size;
        return 0;
    }
    // kSize is a constant expression, so the layout is computed during semantic analysis too
    // (clang -fsyntax-only -Xclang -fdump-record-layouts, used by analyze_file_structs.py).
    template <class T, class Tag> struct Probe { enum { kSize = sizeof(T) }; static int reg; };
    template <class T, class Tag> int Probe<T, Tag>::reg = record(Tag::name(), (unsigned)Probe<T, Tag>::kSize);
}

#define RAN_FSIZE_CAT2(a, b) a##b
#define RAN_FSIZE_CAT(a, b) RAN_FSIZE_CAT2(a, b)
#define RAN_FSIZE_IMPL(T, NAME, TAG)                                                   \
    namespace ran_fsize { struct TAG { static const char* name() { return NAME; } }; } \
    template struct ran_fsize::Probe<T, ran_fsize::TAG>;
#define RAN_FSIZE(T) RAN_FSIZE_IMPL(T, #T, RAN_FSIZE_CAT(ran_fsize_tag_, __COUNTER__))

#include "file_struct_list.inc"

int main()
{
    const std::map<std::string, unsigned>& t = ran_fsize::table();
    for (std::map<std::string, unsigned>::const_iterator it = t.begin(); it != t.end(); ++it)
        std::printf("%s %u\n", it->first.c_str(), it->second);
    return 0;
}
