#!/bin/bash
# port/scripts/build_native.sh - native macOS build of the client.
# Sources come from the .vcxproj files (client_sources.py). Each project is compiled (8 in
# parallel, incremental on source mtime) into a static library, like the Windows build, and the
# libraries are linked against DXVK's d3d9, SDL3 and the system frameworks. Until everything is
# implemented the link fails; its undefined symbols are grouped into docs/port/link-gaps.md.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
BUILD="$ROOT/port/build/native"; mkdir -p "$BUILD/obj" "$BUILD/lib"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
python3 port/scripts/client_sources.py --with-project > "$TMP/sources"

export ROOT BUILD
compile() {   # project<TAB>file
  p="${1%%	*}"; f="${1#*	}"
  o="$BUILD/obj/$(echo "$p" | tr -d '[]')/$(echo "$f" | tr '/[]' '___').o"
  mkdir -p "$(dirname "$o")"
  [ "$o" -nt "$f" ] && exit 0
  case "$f" in
    # C sources get ran_c_compat.h first: fopen with Windows paths resolves like the C++ side.
    *.c) clang -c -O1 -g0 -w -DNDEBUG -I"$ROOT/port/compat/include" -include ran_c_compat.h -I"$(dirname "$f")" "$f" -o "$o" 2>"$o.err" ;;
    *)   RAN_OBJ_OUT="$o" "$ROOT/port/scripts/compile_one.sh" "$f" 3 >/dev/null 2>"$o.err" ;;
  esac
  if [ $? -eq 0 ]; then rm -f "$o.err"; else echo "FAIL	$p	$f"; rm -f "$o"; fi
}
export -f compile
tr '\n' '\0' < "$TMP/sources" | xargs -0 -P 8 -I{} bash -c 'compile "$1"' _ {} | tee "$TMP/fails"
echo "compile failures: $(grep -c FAIL "$TMP/fails")"

# The exe project's own objects are linked directly (as MSVC does - that is what brings in the
# global theApp); the library projects become static archives.
LIBS=()
for d in "$BUILD"/obj/*/; do
  name=$(basename "$d")
  if [ "$name" = "Client__Game" ]; then LIBS+=("$d"*.o); continue; fi
  lib="$BUILD/lib/lib$name.a"
  rm -f "$lib"; ar rcs "$lib" "$d"*.o 2>/dev/null && LIBS+=("$lib")
done

# Platform layer (SDL3 main + hooks) and the D3DX replacement: linked as objects so main()
# pulls the game in.
PLATFORM_OBJS=()
for f in port/platform/*.cpp port/d3dx/*.cpp; do
  o="$BUILD/port_$(basename "$(dirname "$f")")_$(basename "$f" .cpp).o"
  if [ ! "$o" -nt "$f" ]; then
    RAN_OBJ_OUT="$o" port/scripts/compile_one.sh "$f" 5 || { echo "FAIL platform $f"; exit 1; }
  fi
  PLATFORM_OBJS+=("$o")
done

DXVK_LIB="$ROOT/port/third_party/dxvk-install/lib"
SDL="$(brew --prefix sdl3)"
clang++ -o "$BUILD/ran_client" "${PLATFORM_OBJS[@]}" "${LIBS[@]}" \
  -L"$DXVK_LIB" -ldxvk_d3d9 -L"$SDL/lib" -lSDL3 -liconv -lz \
  "$(brew --prefix lzo)/lib/liblzo2.a" \
  "$(brew --prefix libvorbis)/lib/libvorbisfile.a" "$(brew --prefix libvorbis)/lib/libvorbis.a" \
  "$(brew --prefix libogg)/lib/libogg.a" \
  -framework CoreFoundation -framework CoreServices -framework Security \
  -framework CoreText -framework CoreGraphics 2> "$TMP/link.err"
if [ $? -eq 0 ]; then echo "LINKED $BUILD/ran_client"; exit 0; fi

grep -aE '^  "' "$TMP/link.err" | sed -E 's/^  "(.*)", referenced from:.*/\1/; s/^  "(.*)"$/\1/' | sort -u > "$TMP/undef"
xcrun c++filt < "$TMP/undef" | sed -E 's/^_//' > "$TMP/undef.dm"
U=$(wc -l < "$TMP/undef.dm" | tr -d ' ')
[ "$U" -eq 0 ] && { echo "link failed for another reason:"; tail -20 "$TMP/link.err"; exit 1; }
{
  echo "# Native link gaps"
  echo
  echo "Generated by \`port/scripts/build_native.sh\` on $(date +%F): **$U undefined symbols** at the final link"
  echo "(static libraries per project, so only code the client actually reaches is counted)."
  echo
  echo '```'
  cat "$TMP/undef.dm"
  echo '```'
} > docs/port/link-gaps.md
echo "link failed: $U undefined symbols -> docs/port/link-gaps.md"
