#!/bin/bash
# port/scripts/compile_probe.sh — syntax-check every client .cpp natively (same flags as
# compile_one.sh, 8 in parallel) and histogram the first error per failing file.
# Measurement only; it changes no sources. Writes docs/port/compile-probe.md.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
OUT="docs/port/compile-probe.md"
TMP="$(mktemp -d)"
DIRS=("[Lib]__Engine" "[Lib]__EngineUI" "[Lib]__EngineSound" "[Lib]__NetClient" "[Lib]__RanClient" "[Lib]__RanClientUI" "[Lib]__MfcEx" "[Client]__Game")
EXCLUDES="$ROOT/port/native-excludes.txt"
grep -v '^#' "$EXCLUDES" | grep -v '^$' > "$TMP/excludes" || true
find "${DIRS[@]}" -name '*.cpp' | grep -vxF -f "$TMP/excludes" | tr '\n' '\0' > "$TMP/files"
EXCLUDED=$(wc -l < "$TMP/excludes" | tr -d ' ')
TOTAL=$(tr -cd '\0' < "$TMP/files" | wc -c | tr -d ' ')

export TMP ROOT
xargs -0 -P 8 -I{} sh -c '
  f="$1"
  if "$ROOT/port/scripts/compile_one.sh" "$f" 1 >/dev/null 2>"$TMP/err.$$"; then
    echo "OK	$f"
  else
    e=$(grep -a -m1 "error:" "$TMP/err.$$" | sed -E "s/^.*error: //")
    echo "FAIL	$f	$e"
  fi
  rm -f "$TMP/err.$$"
' _ {} < "$TMP/files" > "$TMP/results"

OK=$(grep -c "^OK" "$TMP/results")
{
  echo "# Compile probe (macOS clang, syntax only)"
  echo
  echo "Generated by \`port/scripts/compile_probe.sh\` on $(date +%F). **$OK / $TOTAL files pass** ($EXCLUDED more excluded from the native build, see \`port/native-excludes.txt\`)."
  echo
  echo "## Passing files by project"
  echo
  echo "| Project | Pass | Total |"
  echo "|---|---|---|"
  for d in "${DIRS[@]}"; do
    p=$(grep -F -c "OK	$d/" "$TMP/results"); t=$(grep -F -c "	$d/" "$TMP/results")
    echo "| $d | $p | $t |"
  done
  echo
  echo "## Top first-errors (identifiers normalised to X)"
  echo
  echo "| Count | First error |"
  echo "|---|---|"
  grep "^FAIL" "$TMP/results" | cut -f3 | sed -E "/file not found/!s/'[^']*'/X/g" \
    | sort | uniq -c | sort -rn | head -50 \
    | awk '{c=$1; $1=""; sub(/^ /,""); gsub(/\|/,"\\|"); print "| " c " | " $0 " |"}'
  echo
  echo "## Top missing names (first error per file)"
  echo
  echo "| Count | Name |"
  echo "|---|---|"
  grep "^FAIL" "$TMP/results" | cut -f3 \
    | grep -oE "(undeclared identifier|unknown type name|unknown class name|expected class name|no member named) '[^']+'" \
    | sed -E "s/.*'([^']+)'/\1/" | sort | uniq -c | sort -rn | head -60 \
    | awk '{print "| " $1 " | `" $2 "` |"}'
} > "$OUT"
cp "$TMP/results" /tmp/ran_compile_results.tsv
head -40 "$OUT"
