#!/bin/bash
# port/scripts/compile_probe.sh — syntax-check every client .cpp with macOS clang and
# histogram the first error per file. Measurement only; it changes no sources.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
OUT="docs/port/compile-probe.md"
TMP="$(mktemp -d)"
DIRS=("[Lib]__Engine" "[Lib]__EngineUI" "[Lib]__EngineSound" "[Lib]__NetClient" "[Lib]__RanClient" "[Lib]__RanClientUI" "[Lib]__MfcEx" "[Client]__Game")
INCS=(-Iport/compat/include -IDependency -IDependency/directx -IDependency/NetGlobal)
for d in "${DIRS[@]}"; do
  INCS+=("-I$d")   # each project's pch.h lives in its root
  while IFS= read -r inc; do INCS+=("-I$inc"); done < <(find "$d" -type d -name Sources)
done
: > "$TMP/firsts"
TOTAL=0; OK=0
while IFS= read -r -d '' f; do
  TOTAL=$((TOTAL+1))
  if clang++ -std=c++20 -fsyntax-only -fshort-wchar -fms-extensions -Wno-everything -ferror-limit=1 \
       -include win32_types.h "${INCS[@]}" "$f" 2> "$TMP/err" ; then
    OK=$((OK+1))
  else
    # Keep header names for "file not found" (that's the work queue); normalise other identifiers.
    grep -a -m1 'error:' "$TMP/err" | sed -E 's/^.*error: //' \
      | sed -E '/file not found/!s/'"'"'[^'"'"']*'"'"'/X/g' >> "$TMP/firsts"
  fi
done < <(find "${DIRS[@]}" -name '*.cpp' -print0)
{
  echo "# Compile probe (macOS clang, syntax only)"
  echo
  echo "Generated by \`port/scripts/compile_probe.sh\` on $(date +%F). $OK / $TOTAL files pass."
  echo
  echo "## Top first-errors (identifiers normalised to X)"
  echo
  echo "| Count | First error |"
  echo "|---|---|"
  sort "$TMP/firsts" | uniq -c | sort -rn | head -40 | awk '{c=$1; $1=""; sub(/^ /,""); print "| " c " | " $0 " |"}'
} > "$OUT"
head -25 "$OUT"
