#!/usr/bin/env python3
"""Generates port/tests/golden/struct_list.inc: one RAN_SIZE(<qualified name>) line per struct
defined in the network-message headers (and the few data headers whose structs travel inside
messages). The same list is compiled by MSVC x86 in CI (golden sizes) and by clang on macOS
(port/tests/golden/struct_sizes.cpp), and the two outputs must match.

Usage: gen_struct_sizes.py [--drop name ...]   (names that do not compile anywhere, e.g.
structs inside inactive #ifdef branches, are dropped with --drop and recorded in the .inc)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADERS = sorted((ROOT / "[Lib]__RanClient/Sources/G-Logic/GLMsg").glob("*.h")) + [
    ROOT / "Dependency/NetGlobal/s_NetGlobal.h",
]
OUT = ROOT / "port/tests/golden/struct_list.inc"
# File-format structs read/written as raw bytes (headers included by struct_sizes.cpp).
EXTRA = ["FILECONTEXT"]
# Structs in the message headers that are not byte-serialisable on any platform (they hold C++
# library objects or pointers), so their sizes legitimately differ between MSVC and libc++.
NON_WIRE = {
    "GLCHARAG_DATA": "agent-server character data, holds std::map/std::vector",
    "SHOPPURCHASE": "server shop record, holds std::string",
    "PER_IO_OPERATION_DATA": "server IOCP bookkeeping (OVERLAPPED, buffer pointers)",
    "STracingData": "holds std::string",
    "NET_UPDATE_TRACINGCHAR": "holds std::string; the client only reads updateNum (offset 8, same on both)",
    "NET_UPDATE_TRACINGCHAR_ALL": "holds std::string; GM tracing list, not read by the client",
}

TOKEN = re.compile(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|//[^\n]*|/\*.*?\*/|#[^\n]*|[A-Za-z_]\w*|::|[{};<>()]|\S', re.S)


def structs_in(path):
    text = path.read_bytes().decode("cp949", errors="replace")
    toks = [t for t in TOKEN.findall(text) if not t.startswith(("//", "/*", "#", '"', "'"))]
    scope = []          # entries: name (namespace/struct) or None (other braces)
    pending = None      # name of the namespace/struct whose '{' comes next
    found = []
    i = 0
    while i < len(toks):
        t = toks[i]
        if t in ("namespace", "struct", "class") and i + 1 < len(toks) and re.match(r"[A-Za-z_]\w*$", toks[i + 1]):
            name = toks[i + 1]
            templ = i >= 1 and toks[i - 1] == ">"   # template<...> struct X
            # find what follows the name: '{', ':' base list then '{', or ';' / something else
            j = i + 2
            while j < len(toks) and toks[j] not in ("{", ";", "(", ")", "<", ">"):
                j += 1
            if j < len(toks) and toks[j] == "{":
                pending = name
                if t != "namespace" and not templ and None not in scope:
                    found.append("::".join([s for s in scope] + [name]))
                i = j
                continue
            i += 2
            continue
        if t == "{":
            scope.append(pending)
            pending = None
        elif t == "}":
            if scope:
                scope.pop()
        i += 1
    return found


def main():
    drops = set()
    if "--drop" in sys.argv:
        drops = set(sys.argv[sys.argv.index("--drop") + 1:])
    if OUT.exists():   # keep earlier drops
        for line in OUT.read_text().splitlines():
            m = re.match(r"// dropped: (\S+)", line)
            if m:
                drops.add(m.group(1))
    names = list(EXTRA)
    for h in HEADERS:
        for n in structs_in(h):
            if n not in names:
                names.append(n)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = ["// Generated by port/scripts/gen_struct_sizes.py - do not edit.",
             "// Network-message structs whose byte layout must be identical on Windows x86 and macOS."]
    lines += [f"// dropped: {d}" for d in sorted(drops)]
    lines += [f"// not a wire struct: {n} - {why}" for n, why in sorted(NON_WIRE.items())]
    lines += [f"RAN_SIZE({n})" for n in names if n not in drops and n not in NON_WIRE]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(names) - len(drops & set(names))} structs -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
