#!/usr/bin/env python3
"""Count the Windows-only APIs the RAN client uses. Read-only; sources are CP949, read as latin-1."""
import collections
import pathlib
import re
import sys

CLIENT_DIRS = [
    "[Client]__Game", "[Lib]__Engine", "[Lib]__EngineSound", "[Lib]__EngineUI",
    "[Lib]__MfcEx", "[Lib]__NetClient", "[Lib]__RanClient", "[Lib]__RanClientUI",
]

PATTERNS = {
    "d3d9_method": re.compile(r"\b(?:\w*[Dd]evice\w*|pd3d\w*|m_pd3d\w*)\s*->\s*([A-Z]\w+)\s*\("),
    "d3dx_call": re.compile(r"\b(D3DX[A-Z]\w*)\s*\("),
    "win32_call": re.compile(
        r"\b(CreateThread|_beginthreadex|EnterCriticalSection|InitializeCriticalSection|"
        r"WaitForSingleObject|GetTickCount|timeGetTime|QueryPerformanceCounter|"
        r"RegOpenKeyEx\w*|RegQueryValueEx\w*|CreateFile\w*|GetModuleFileName\w*|"
        r"MessageBox\w*|PostMessage\w*|SendMessage\w*|GetAsyncKeyState|Imm[A-Z]\w*|"
        r"WSAEventSelect|ioctlsocket|DirectSoundCreate\w*|DirectInput8Create|"
        r"MultiByteToWideChar|WideCharToMultiByte)\s*\("),
    "mfc_type": re.compile(
        r"\b(CString|CWinApp|CWnd|CFile|CArray|CList|CMap|CPoint|CRect|CSize|CTime|"
        r"AfxGetApp|AfxMessageBox)\b"),
}
CATEGORIES = list(PATTERNS)
SUFFIXES = {".cpp", ".h", ".hpp", ".inl"}


def scan(root, dirs):
    counts = {k: collections.Counter() for k in CATEGORIES}
    for d in dirs:
        for path in sorted(pathlib.Path(root, d).rglob("*")):
            if path.suffix.lower() not in SUFFIXES or not path.is_file():
                continue
            text = path.read_text(encoding="latin-1")
            for key, pat in PATTERNS.items():
                counts[key].update(pat.findall(text))
    return counts


def render(counts):
    out = ["# RAN client Windows API inventory", "",
           "Generated by `port/scripts/inventory.py`. Re-run after each compat milestone.", ""]
    for key in CATEGORIES:
        c = counts[key]
        out += [f"## {key}", "", f"{len(c)} distinct, {sum(c.values())} uses.", "",
                "| Name | Uses |", "|---|---|"]
        out += [f"| {name} | {n} |" for name, n in c.most_common()]
        out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    print(render(scan(root, CLIENT_DIRS)))
