USE RanGame1;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `ChaFriend` (
  `ChaFriendNum` INT NOT NULL AUTO_INCREMENT,
  `ChaP` INT NOT NULL,
  `ChaS` INT NOT NULL,
  `ChaFlag` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ChaFriendNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ChaFriendBackup` (
  `ChaFriendNum` INT NOT NULL AUTO_INCREMENT,
  `ChaP` INT NOT NULL,
  `ChaS` INT NOT NULL,
  `ChaFlag` INT NOT NULL,
  KEY `idx_ai_ChaFriendNum` (`ChaFriendNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ChaInfo` (
  `ChaNum` INT NOT NULL AUTO_INCREMENT,
  `SGNum` INT DEFAULT 0,
  `UserNum` INT NOT NULL,
  `GuNum` INT DEFAULT 0,
  `GuPosition` INT NOT NULL DEFAULT 0,
  `ChaName` VARCHAR(33) CHARACTER SET utf8mb4 NOT NULL,
  `ChaGuName` VARCHAR(33) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `ChaTribe` INT NOT NULL DEFAULT 0,
  `ChaClass` INT NOT NULL DEFAULT 0,
  `ChaSchool` INT NOT NULL DEFAULT 0,
  `ChaSex` TINYINT UNSIGNED,
  `ChaHair` INT NOT NULL DEFAULT 0,
  `ChaHairColor` INT,
  `ChaFace` INT NOT NULL DEFAULT 0,
  `ChaLiving` INT NOT NULL DEFAULT 0,
  `ChaLevel` INT NOT NULL DEFAULT 0,
  `ChaMoney` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `ChaPower` BIGINT NOT NULL DEFAULT 0,
  `ChaStrong` BIGINT NOT NULL DEFAULT 0,
  `ChaStrength` BIGINT NOT NULL DEFAULT 0,
  `ChaSpirit` BIGINT NOT NULL DEFAULT 0,
  `ChaDex` BIGINT NOT NULL DEFAULT 0,
  `ChaIntel` INT NOT NULL DEFAULT 0,
  `ChaStRemain` BIGINT NOT NULL DEFAULT 0,
  `ChaExp` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `ChaViewRange` BIGINT NOT NULL DEFAULT 0,
  `ChaHP` BIGINT NOT NULL DEFAULT 0,
  `ChaMP` BIGINT NOT NULL DEFAULT 0,
  `ChaStartMap` INT NOT NULL DEFAULT 0,
  `ChaStartGate` INT NOT NULL DEFAULT 0,
  `ChaPosX` DOUBLE NOT NULL DEFAULT 0,
  `ChaPosY` DOUBLE NOT NULL DEFAULT 0,
  `ChaPosZ` DOUBLE NOT NULL DEFAULT 0,
  `ChaSaveMap` INT NOT NULL DEFAULT -1,
  `ChaSavePosX` DOUBLE NOT NULL DEFAULT 0,
  `ChaSavePosY` DOUBLE NOT NULL DEFAULT 0,
  `ChaSavePosZ` DOUBLE NOT NULL DEFAULT 0,
  `ChaReturnMap` INT NOT NULL DEFAULT -1,
  `ChaReturnPosX` DOUBLE NOT NULL DEFAULT 0,
  `ChaReturnPosY` DOUBLE NOT NULL DEFAULT 0,
  `ChaReturnPosZ` DOUBLE NOT NULL DEFAULT 0,
  `ChaBright` INT NOT NULL DEFAULT 0,
  `ChaAttackP` INT NOT NULL DEFAULT 0,
  `ChaDefenseP` INT NOT NULL DEFAULT 0,
  `ChaFightA` INT NOT NULL DEFAULT 0,
  `ChaShootA` INT NOT NULL DEFAULT 0,
  `ChaSP` BIGINT NOT NULL DEFAULT 0,
  `ChaPK` INT NOT NULL DEFAULT 0,
  `ChaSkillPoint` INT NOT NULL DEFAULT 0,
  `ChaInvenLine` INT NOT NULL DEFAULT 0,
  `ChaDeleted` INT NOT NULL DEFAULT 0,
  `ChaOnline` INT NOT NULL DEFAULT 0,
  `ChaCreateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ChaDeletedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ChaStorage2` DATETIME NOT NULL DEFAULT '1970-02-01',
  `ChaStorage3` DATETIME NOT NULL DEFAULT '1970-02-01',
  `ChaStorage4` DATETIME NOT NULL DEFAULT '1970-02-01',
  `ChaGuSecede` DATETIME NOT NULL DEFAULT '1970-02-01',
  `ChaQuest` LONGBLOB,
  `ChaSkills` LONGBLOB,
  `ChaSkillSlot` LONGBLOB,
  `ChaActionSlot` LONGBLOB,
  `ChaPutOnItems` LONGBLOB,
  `ChaInven` LONGBLOB,
  `ChaReExp` DOUBLE,
  `ChaReborn` INT NOT NULL DEFAULT 0,
  `ChaSpecial` SMALLINT DEFAULT 0,
  `ChaKill` INT NOT NULL DEFAULT 0,
  `ChaRebornReset` INT NOT NULL DEFAULT 0,
  `ChangeClass` INT NOT NULL DEFAULT 0,
  `ChaKills` INT NOT NULL DEFAULT 0,
  `GraveYard` INT NOT NULL DEFAULT 0,
  `ChaCoolTime` LONGBLOB,
  `FixInject` VARCHAR(33) CHARACTER SET utf8mb4,
  `AuctionTimeOut` VARBINARY(50),
  `ChaSpSID` INT DEFAULT 0,
  `ChaSpMID` INT DEFAULT 0,
  `ChaCP` INT DEFAULT 0,
  `SumSub` INT DEFAULT 0,
  `SumMain` INT DEFAULT 0,
  `UserLastInfo` INT DEFAULT 0,
  PRIMARY KEY (`ChaNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ChaLastInfo` (
  `ChaNum` INT NOT NULL DEFAULT 0,
  `ChaLevel` INT NOT NULL DEFAULT 0,
  `ChaMoney` DECIMAL(19,4) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ChaNameInfo` (
  `ChaNameNum` INT NOT NULL AUTO_INCREMENT,
  `ChaNum` INT NOT NULL DEFAULT 0,
  `ChaName` VARCHAR(33) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  PRIMARY KEY (`ChaNameNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `GuildAlliance` (
  `GuNumP` INT NOT NULL DEFAULT 0,
  `GuNumS` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`GuNumP`,`GuNumS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `GuildBattle` (
  `GuBattleNum` INT NOT NULL AUTO_INCREMENT,
  `GuSNum` INT DEFAULT 0,
  `GuPNum` INT DEFAULT 0,
  `GuAlliance` INT DEFAULT 0,
  `GuFlag` INT DEFAULT 0,
  `GuKillNum` INT DEFAULT 0,
  `GuDeathNum` INT,
  `GuBattleStartDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `GuBattleEndDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_ai_GuBattleNum` (`GuBattleNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `GuildInfo` (
  `GuNum` INT NOT NULL AUTO_INCREMENT,
  `ChaNum` INT NOT NULL DEFAULT 0,
  `GuDeputy` INT NOT NULL DEFAULT 0,
  `GuName` VARCHAR(33) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `GuNotice` VARCHAR(401) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `GuRank` INT NOT NULL DEFAULT 0,
  `GuMoney` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `GuIncomeMoney` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `GuMarkVer` INT NOT NULL DEFAULT 0,
  `GuExpire` INT NOT NULL DEFAULT 0,
  `GuMakeTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `GuExpireTime` DATETIME NOT NULL DEFAULT '1970-02-01',
  `GuAllianceSec` DATETIME NOT NULL DEFAULT '1970-02-01',
  `GuAllianceDis` DATETIME NOT NULL DEFAULT '1970-02-01',
  `GuMarkImage` LONGBLOB NOT NULL DEFAULT (''),
  `GuStorage` LONGBLOB NOT NULL DEFAULT (''),
  `GuAuthorityTime` DATETIME NOT NULL DEFAULT '1970-02-01',
  `GuAllianceBattleLose` INT NOT NULL DEFAULT 0,
  `GuAllianceBattleDraw` INT NOT NULL DEFAULT 0,
  `GuAllianceBattleWin` INT NOT NULL DEFAULT 0,
  `GuBattleLastTime` DATETIME NOT NULL DEFAULT '1970-02-01',
  `GuBattleLose` INT NOT NULL DEFAULT 0,
  `GuBattleDraw` INT NOT NULL DEFAULT 0,
  `GuBattleWin` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`GuNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `GuildRegion` (
  `RegionID` INT NOT NULL,
  `GuNum` INT NOT NULL DEFAULT 0,
  `RegionTax` DOUBLE NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`RegionID`,`GuNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ItemCustomize` (
  `GMID` INT NOT NULL AUTO_INCREMENT,
  `MainID` INT NOT NULL,
  `SubID` INT NOT NULL,
  `ItemName` VARCHAR(255) CHARACTER SET utf8mb4,
  `ChangeQuantity` TINYINT(1) NOT NULL DEFAULT 0,
  `AttackUpgrade` TINYINT(1) NOT NULL DEFAULT 0,
  `DefenceUpgrade` TINYINT(1) NOT NULL DEFAULT 0,
  `ChaInven` LONGBLOB,
  `Point` BIGINT NOT NULL DEFAULT 0,
  `AddDate` INT NOT NULL DEFAULT 0,
  `GmType` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '其它',
  `EditBol` TINYINT(1) NOT NULL DEFAULT 0,
  `GfInfo` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT '0||0||0||0',
  `GmShuXing` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'Null|Null||Null|Null||Null|Null||Null|Null',
  `GmPic` VARCHAR(100) CHARACTER SET utf8mb4,
  `AddBol` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`GMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PetInfo` (
  `PetNum` INT NOT NULL DEFAULT 0,
  `PetName` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `PetChaNum` INT NOT NULL DEFAULT 0,
  `PetType` INT NOT NULL DEFAULT 0,
  `PetMID` INT NOT NULL DEFAULT 0,
  `PetSID` INT NOT NULL DEFAULT 0,
  `PetStyle` INT NOT NULL DEFAULT 0,
  `PetColor` INT NOT NULL DEFAULT 0,
  `PetFull` INT NOT NULL DEFAULT 1000,
  `PetDeleted` INT NOT NULL DEFAULT 0,
  `PetCreateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PetDeletedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PetPutOnItems` LONGBLOB NOT NULL DEFAULT (''),
  `PetCardMID` INT NOT NULL DEFAULT 0,
  `PetCardSID` INT NOT NULL DEFAULT 0,
  `PetUniqueNum` INT NOT NULL AUTO_INCREMENT,
  `PetSkinStartDate` DATETIME,
  `PetSkinTime` DATETIME,
  `PetSkinScale` INT,
  `PetSkinSID` INT,
  `PetSkinMID` INT,
  PRIMARY KEY (`PetUniqueNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PetInven` (
  `PetInvenNum` INT NOT NULL AUTO_INCREMENT,
  `PetNum` INT NOT NULL DEFAULT 0,
  `PetInvenType` INT NOT NULL DEFAULT 0,
  `PetInvenMID` INT NOT NULL DEFAULT 0,
  `PetInvenSID` INT NOT NULL DEFAULT 0,
  `PetInvenCMID` INT NOT NULL DEFAULT 0,
  `PetInvenCSID` INT NOT NULL DEFAULT 0,
  `PetInvenAvailable` INT NOT NULL DEFAULT 0,
  `PetInvenUpdateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PetChaNum` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`PetInvenNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PetStyleFlag` (
  `PetStyle` INT NOT NULL,
  `PetStyleName` VARCHAR(2) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`PetStyle`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PetTypeFlag` (
  `PetType` INT NOT NULL,
  `PetName` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`PetType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SkillTableRef` (
  `SkillNo` INT NOT NULL AUTO_INCREMENT,
  `MID` INT NOT NULL,
  `SID` INT NOT NULL,
  `SkillName` CHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `SkillDes` CHAR(200) CHARACTER SET utf8mb4,
  `SkillClass` INT,
  `SkillLevelReq` INT,
  `SkillDexReq` INT,
  `SkillStrongReq` INT,
  `SkillIntReq` INT,
  PRIMARY KEY (`SkillNo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `UserInven` (
  `UserInvenNum` INT NOT NULL AUTO_INCREMENT,
  `UserNum` INT NOT NULL,
  `SGNum` INT NOT NULL,
  `ChaStorage2` DATETIME NOT NULL DEFAULT '1970-02-01',
  `ChaStorage3` DATETIME NOT NULL DEFAULT '1970-02-01',
  `ChaStorage4` DATETIME NOT NULL DEFAULT '1970-02-01',
  `UserMoney` DECIMAL(19,4) NOT NULL,
  `UserInven` LONGBLOB,
  PRIMARY KEY (`UserInvenNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `UserLastInfo` (
  `UserNum` INT NOT NULL DEFAULT 0,
  `UserMoney` DECIMAL(19,4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VehicleInfo` (
  `VehicleUniqueNum` INT NOT NULL AUTO_INCREMENT,
  `VehicleNum` INT NOT NULL DEFAULT 0,
  `VehicleName` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `VehicleChaNum` INT NOT NULL DEFAULT 0,
  `VehicleType` INT NOT NULL DEFAULT 0,
  `VehicleCardMID` INT NOT NULL DEFAULT 0,
  `VehicleCardSID` INT NOT NULL DEFAULT 0,
  `VehicleBattery` INT NOT NULL DEFAULT 1000,
  `VehicleDeleted` INT NOT NULL DEFAULT 0,
  `VehicleCreateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VehicleDeletedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VehiclePutOnItems` LONGBLOB NOT NULL DEFAULT (''),
  PRIMARY KEY (`VehicleUniqueNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

