USE RanUser;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `AccountInfo` (
  `AccountNum` INT NOT NULL AUTO_INCREMENT,
  `BankName` VARCHAR(30) CHARACTER SET utf8mb4,
  `BankNumber` VARCHAR(50) CHARACTER SET utf8mb4,
  `AccountOwner` VARCHAR(30) CHARACTER SET utf8mb4,
  KEY `idx_ai_AccountNum` (`AccountNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `BlockAddress` (
  `BlockIdx` INT NOT NULL AUTO_INCREMENT,
  `BlockAddress` VARCHAR(23) CHARACTER SET utf8mb4 NOT NULL,
  `BlockReason` VARCHAR(256) CHARACTER SET utf8mb4,
  `BlockDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`BlockIdx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `CheckId` (
  `Num` INT NOT NULL AUTO_INCREMENT,
  `Id` VARCHAR(18) CHARACTER SET utf8mb4 NOT NULL,
  `CreateDate` DATETIME,
  PRIMARY KEY (`Id`),
  KEY `idx_ai_Num` (`Num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `DaumLogGameTime` (
  `GameTimeNum` INT NOT NULL AUTO_INCREMENT,
  `LogDate` DATETIME NOT NULL,
  `GameTime` INT NOT NULL,
  `UserUID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `ChaNum` INT,
  `UserNum` INT NOT NULL,
  `SGNum` INT,
  `SvrNum` INT,
  KEY `idx_ai_GameTimeNum` (`GameTimeNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `DaumLogLogin` (
  `LoginNum` INT NOT NULL AUTO_INCREMENT,
  `UserNum` INT NOT NULL,
  `UserUID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `LogInOut` INT NOT NULL,
  `LogDate` DATETIME,
  `LogIpAddress` VARCHAR(23) CHARACTER SET utf8mb4,
  KEY `idx_ai_LoginNum` (`LoginNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `DaumUserInfo` (
  `UserNum` INT NOT NULL AUTO_INCREMENT,
  `UserUID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `UserGID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `SSNHEAD` VARCHAR(8) CHARACTER SET utf8mb4 NOT NULL,
  `SEX` VARCHAR(3) CHARACTER SET utf8mb4 NOT NULL,
  `UserType` INT NOT NULL,
  `UserLoginState` INT NOT NULL,
  `UserAvailable` INT NOT NULL,
  `CreateDate` DATETIME NOT NULL,
  `LastLoginDate` DATETIME NOT NULL,
  `SGNum` INT,
  `SvrNum` INT,
  `ChaName` VARCHAR(33) CHARACTER SET utf8mb4,
  `UserBlock` INT NOT NULL,
  `UserBlockDate` DATETIME NOT NULL,
  `ChaRemain` INT,
  `ChaTestRemain` INT,
  `PremiumDate` DATETIME NOT NULL,
  `ChatBlockDate` DATETIME NOT NULL,
  KEY `idx_ai_UserNum` (`UserNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Donation` (
  `Name` VARCHAR(50) CHARACTER SET utf8mb4,
  `Tnum` BIGINT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME,
  `Item` VARCHAR(50) CHARACTER SET utf8mb4,
  `Quantity` VARCHAR(50) CHARACTER SET utf8mb4,
  `Duration` VARCHAR(50) CHARACTER SET utf8mb4,
  `Usernum` BIGINT,
  KEY `idx_ai_Tnum` (`Tnum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `donator_itemlst` (
  `ItemNum` INT NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(80) CHARACTER SET utf8mb4,
  `ItemData` VARBINARY(200),
  KEY `idx_ai_ItemNum` (`ItemNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Fullclient` (
  `link_name` VARCHAR(100) CHARACTER SET utf8mb4,
  `link_address` LONGTEXT,
  `link_description` LONGTEXT,
  `link_id` VARCHAR(100) CHARACTER SET utf8mb4,
  `link_date` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fullclientsplit` (
  `link_name` VARCHAR(100) CHARACTER SET utf8mb4,
  `link_address` LONGTEXT,
  `link_description` LONGTEXT,
  `link_id` VARCHAR(100) CHARACTER SET utf8mb4,
  `link_date` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `FullUserInfo` (
  `UserNum` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `UserID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `UserPass` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `UserPass2` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `BodyID` VARCHAR(18) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `Sex` VARCHAR(2) CHARACTER SET utf8mb4 NOT NULL,
  `Email` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `BirthY` VARCHAR(4) CHARACTER SET utf8mb4 NOT NULL,
  `BirthM` VARCHAR(2) CHARACTER SET utf8mb4 NOT NULL,
  `BirthD` VARCHAR(2) CHARACTER SET utf8mb4 NOT NULL,
  `TEL` VARCHAR(15) CHARACTER SET utf8mb4 NOT NULL,
  `Mobile` VARCHAR(13) CHARACTER SET utf8mb4,
  `QQ` VARCHAR(13) CHARACTER SET utf8mb4,
  `MSN` VARCHAR(50) CHARACTER SET utf8mb4,
  `City1` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `City2` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `Post` VARCHAR(6) CHARACTER SET utf8mb4,
  `Address` VARCHAR(60) CHARACTER SET utf8mb4,
  `SafeId` VARCHAR(12) CHARACTER SET utf8mb4 NOT NULL,
  `BodyID2` VARCHAR(18) CHARACTER SET utf8mb4,
  KEY `idx_ai_UserNum` (`UserNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `gmc` (
  `username` VARCHAR(50) CHARACTER SET utf8mb4,
  `session` LONGTEXT,
  `sesexp` LONGTEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `HelpDesk` (
  `TicketNum` INT NOT NULL,
  `UserName` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `Subject` VARCHAR(40) CHARACTER SET utf8mb4 NOT NULL,
  `Severity` INT NOT NULL,
  `Problem` VARCHAR(5000) CHARACTER SET utf8mb4,
  `Date` DATETIME NOT NULL,
  `CaseStatus` INT NOT NULL,
  `Reply` VARCHAR(5000) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `htlog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aname` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `IPAddress` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `LogDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `IPInfo` (
  `IpAddress` VARCHAR(23) CHARACTER SET utf8mb4 NOT NULL,
  `UserNum` INT NOT NULL,
  `IdxIP` INT NOT NULL AUTO_INCREMENT,
  `UseAvailable` INT,
  PRIMARY KEY (`IdxIP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `item` (
  `ItemID` VARCHAR(50) CHARACTER SET utf8mb4,
  `ItemMain` VARCHAR(50) CHARACTER SET utf8mb4,
  `ItemSub` VARCHAR(50) CHARACTER SET utf8mb4,
  `ItemName` LONGTEXT,
  `ItemDescription` LONGTEXT,
  `ItemImage` VARCHAR(50) CHARACTER SET utf8mb4,
  `ItemNum` BIGINT NOT NULL AUTO_INCREMENT,
  KEY `idx_ai_ItemNum` (`ItemNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogAction` (
  `ActionNum` BIGINT NOT NULL AUTO_INCREMENT,
  `ChaNum` INT NOT NULL DEFAULT 0,
  `Type` INT NOT NULL DEFAULT 0,
  `TargetNum` INT NOT NULL DEFAULT 0,
  `TargetType` INT NOT NULL DEFAULT 0,
  `BrightPoint` INT NOT NULL DEFAULT 0,
  `LifePoint` INT NOT NULL DEFAULT 0,
  `ExpPoint` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `ActionMoney` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `ActionDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ActionNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogGameTime` (
  `GameTimeNum` BIGINT NOT NULL AUTO_INCREMENT,
  `LogDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `GameTime` INT NOT NULL DEFAULT 0,
  `UserID` VARCHAR(20) CHARACTER SET utf8mb4,
  `UserNum` INT DEFAULT 0,
  `SGNum` INT DEFAULT 0,
  `SvrNum` INT DEFAULT 0,
  `ChaNum` INT DEFAULT 0,
  PRIMARY KEY (`GameTimeNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogGmCmd` (
  `GmCmdNum` INT NOT NULL AUTO_INCREMENT,
  `LogDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `GmCmd` VARCHAR(200) CHARACTER SET utf8mb4,
  `UserNum` INT,
  `userip` VARCHAR(50) CHARACTER SET utf8mb4,
  PRIMARY KEY (`GmCmdNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LoginFails` (
  `IP` VARCHAR(20) CHARACTER SET utf8mb4,
  `UserID` VARCHAR(50) CHARACTER SET utf8mb4,
  `Time` VARCHAR(50) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogLogin` (
  `LoginNum` BIGINT NOT NULL AUTO_INCREMENT,
  `UserNum` INT NOT NULL,
  `UserID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `LogInOut` INT NOT NULL DEFAULT 0,
  `LogDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `LogIpAddress` VARCHAR(23) CHARACTER SET utf8mb4,
  PRIMARY KEY (`LoginNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogServerState` (
  `SvrStateNum` INT NOT NULL AUTO_INCREMENT,
  `LogDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UserNum` INT NOT NULL DEFAULT 0,
  `UserMaxNum` INT NOT NULL DEFAULT 0,
  `SvrNum` INT NOT NULL DEFAULT 0,
  `SGNum` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`SvrStateNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LVList` (
  `lvid` INT NOT NULL AUTO_INCREMENT,
  `Chaskill` INT,
  `Chalevel` INT,
  `ChaRemain` INT,
  PRIMARY KEY (`lvid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Manage` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `UserPass` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `UserQX` VARCHAR(100) CHARACTER SET utf8mb4,
  `online` CHAR(10) CHARACTER SET utf8mb4,
  KEY `idx_ai_ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MuWeb_des_vote` (
  `vote_name` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
  `vote_link` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
  `vote_img` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
  `vote_date` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
  `vote_unid` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MuWeb_des_vote_count_acc` (
  `vote_acc` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_count` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_newdate` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_newhour` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_id` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MuWeb_des_vote_hours` (
  `vote_hours` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_how` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MuWeb_des_vote_log` (
  `memb___id` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_credits` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_resets` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_levels` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_date` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_link` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_ip` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MuWeb_des_vote_logs` (
  `memb___id` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_what` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_date` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_link` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_alink` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_ip` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `unid` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MuWeb_des_vote_set` (
  `vote_credit` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_credits` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_reset` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_resets` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_level` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_levels` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_lvlup` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `vote_lvlupmg` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `max_level` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `max_reset` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `max_credits` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `newcheckid` (
  `Id` VARCHAR(18) CHARACTER SET utf8mb4 NOT NULL,
  `CreateDate` DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `NewType` (
  `id` INT NOT NULL,
  `TypeName` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `lx` VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PassCheckLog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ts` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `uid` VARCHAR(50) CHARACTER SET utf8mb4,
  `pw` VARCHAR(50) CHARACTER SET utf8mb4,
  `nation` INT,
  `ret` INT,
  KEY `idx_ai_id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `patches` (
  `link_name` VARCHAR(100) CHARACTER SET utf8mb4,
  `link_address` LONGTEXT,
  `link_description` LONGTEXT,
  `link_id` VARCHAR(100) CHARACTER SET utf8mb4,
  `link_date` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `plusx` (
  `PlusID` INT,
  `Plus` VARCHAR(50) CHARACTER SET utf8mb4,
  `Hex` VARCHAR(50) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rvslot` (
  `id` INT,
  `rvslot` VARCHAR(50) CHARACTER SET utf8mb4,
  `hex` VARCHAR(50) CHARACTER SET utf8mb4,
  `hexnum` VARCHAR(2) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ServerGroup` (
  `SGNum` INT NOT NULL,
  `SGName` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `OdbcName` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `OdbcUserID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `OdbcPassword` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `OdbcLogName` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `OdbcLogUserID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `OdbcLogPassword` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  PRIMARY KEY (`SGNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ServerInfo` (
  `SGNum` INT NOT NULL,
  `SvrNum` INT NOT NULL,
  `SvrType` INT NOT NULL,
  PRIMARY KEY (`SvrNum`,`SGNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ShopGoumaiInfo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ChaNum` INT NOT NULL,
  `UserNum` INT NOT NULL,
  `UserID` VARCHAR(50) CHARACTER SET utf8mb4,
  `GMID` INT NOT NULL,
  `ItemName` VARCHAR(100) CHARACTER SET utf8mb4,
  `MainID` INT NOT NULL,
  `usbID` INT NOT NULL,
  `ItemPoint` BIGINT NOT NULL,
  `ItemDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `skill` (
  `SDN` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillMain` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillSub` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillName` VARCHAR(100) CHARACTER SET utf8mb4,
  `SkillImage` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillDescription` LONGTEXT,
  `SkillType` INT,
  `SkillStyle` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Skills` (
  `SkillNum` INT NOT NULL AUTO_INCREMENT,
  `SkillMain` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillSub` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillName` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillImage` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillDescription` VARCHAR(150) CHARACTER SET utf8mb4,
  `SkillType` INT,
  `SkillChar` INT,
  `SkillCost` INT NOT NULL DEFAULT 0,
  `SkillKey` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillReq` VARCHAR(50) CHARACTER SET utf8mb4,
  `SkillLevel` INT,
  `SkillGender` INT,
  KEY `idx_ai_SkillNum` (`SkillNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SqlInjectionLog` (
  `LastDate` VARCHAR(50) CHARACTER SET utf8mb4,
  `SqlInject` VARCHAR(50) CHARACTER SET utf8mb4,
  `HostIp` VARCHAR(50) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `StatGameTime` (
  `GYear` INT NOT NULL DEFAULT 0,
  `GMonth` INT NOT NULL DEFAULT 0,
  `GDay` INT NOT NULL DEFAULT 0,
  `GTime` INT DEFAULT 0,
  PRIMARY KEY (`GYear`,`GMonth`,`GDay`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `StatLogin` (
  `LYear` INT NOT NULL DEFAULT 0,
  `LMonth` INT NOT NULL DEFAULT 0,
  `LDay` INT NOT NULL DEFAULT 0,
  `LHour` INT NOT NULL DEFAULT 0,
  `LCount` INT DEFAULT 1,
  PRIMARY KEY (`LYear`,`LMonth`,`LDay`,`LHour`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `sysdiagrams` (
  `name` VARCHAR(128) CHARACTER SET utf8mb4 NOT NULL,
  `principal_id` INT NOT NULL,
  `diagram_id` INT NOT NULL AUTO_INCREMENT,
  `version` INT,
  `definition` LONGBLOB,
  PRIMARY KEY (`diagram_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TopUp` (
  `Code` VARCHAR(20) CHARACTER SET utf8mb4,
  `CodePinCode` VARCHAR(20) CHARACTER SET utf8mb4,
  `CodeValue` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `traceip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ua` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,
  `ip` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  `datetime` INT NOT NULL,
  `cpt` INT NOT NULL DEFAULT 0,
  `locked` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `traceip_cfg` (
  `var` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,
  `val` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`var`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `TransactionLogs` (
  `TransactionID` INT NOT NULL,
  `UserName` VARCHAR(50) CHARACTER SET utf8mb4,
  `FunctionRecord` VARCHAR(50) CHARACTER SET utf8mb4,
  `DateRecord` VARCHAR(50) CHARACTER SET utf8mb4,
  `PointsCost` VARCHAR(50) CHARACTER SET utf8mb4,
  `PointsAdd` VARCHAR(50) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `UserInfo` (
  `UserNum` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `UserID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `UserPass` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `UserPass2` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  `UserType` INT NOT NULL DEFAULT 1,
  `UserLoginState` INT NOT NULL DEFAULT 0,
  `UserAvailable` INT DEFAULT 1,
  `CreateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastLoginDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` DATETIME DEFAULT '1970-02-01',
  `UserAge` INT DEFAULT 0,
  `OfflineTime` INT NOT NULL DEFAULT 0,
  `GameTime` INT DEFAULT -99999999,
  `SGNum` INT DEFAULT 0,
  `SvrNum` INT DEFAULT 0,
  `ChaName` VARCHAR(33) CHARACTER SET utf8mb4 DEFAULT '',
  `UserBlock` INT NOT NULL DEFAULT 0,
  `UserBlockDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ChaRemain` INT NOT NULL DEFAULT 2,
  `ChaTestRemain` INT NOT NULL DEFAULT 2,
  `PremiumDate` DATETIME NOT NULL DEFAULT '1970-02-01',
  `ChatBlockDate` DATETIME NOT NULL DEFAULT '1970-02-01',
  `NewUserPass` VARCHAR(50) CHARACTER SET utf8mb4,
  `NewUserPass1` VARCHAR(50) CHARACTER SET utf8mb4,
  `tj` VARCHAR(50) CHARACTER SET utf8mb4,
  `online` VARCHAR(50) CHARACTER SET utf8mb4,
  `Email` VARCHAR(50) CHARACTER SET utf8mb4,
  `PinCodes` VARCHAR(50) CHARACTER SET utf8mb4,
  `IPCount` INT,
  `UserEmail` VARCHAR(50) CHARACTER SET utf8mb4,
  `UserPoint` INT,
  `WebLoginState` INT NOT NULL DEFAULT 0,
  `Upass` VARCHAR(50) CHARACTER SET utf8mb4,
  `IpSite` VARCHAR(50) CHARACTER SET utf8mb4,
  `Donated` VARCHAR(50) CHARACTER SET utf8mb4,
  `GameTime2` INT NOT NULL DEFAULT 0,
  `UserVIP` INT NOT NULL DEFAULT 0,
  `UserPoint2` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `UserLastInfo` (
  `UserNum` INT,
  `UserMoney` DECIMAL(19,4) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `UserPoint` (
  `UserNum` INT NOT NULL,
  `Point` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `UserPointLog` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `userNum` BIGINT,
  `Point` BIGINT,
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VLog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ts` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `uid` VARCHAR(50) CHARACTER SET utf8mb4,
  `pw` VARCHAR(50) CHARACTER SET utf8mb4,
  `pwlen` INT,
  `stored` VARCHAR(50) CHARACTER SET utf8mb4,
  `matched` INT,
  KEY `idx_ai_id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(100) CHARACTER SET utf8mb4,
  `username` VARCHAR(50) CHARACTER SET utf8mb4,
  `votetime` INT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VoteAccountLog` (
  `VoteUserName` VARCHAR(50) CHARACTER SET utf8mb4,
  `VoteCount` VARCHAR(50) CHARACTER SET utf8mb4,
  `VoteDate` VARCHAR(50) CHARACTER SET utf8mb4,
  `VoteHour` VARCHAR(50) CHARACTER SET utf8mb4,
  `VoteID` VARCHAR(50) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VoteCountLog` (
  `VoteLog` VARCHAR(50) CHARACTER SET utf8mb4,
  `VoteCount` VARCHAR(50) CHARACTER SET utf8mb4,
  `VoteDate` VARCHAR(50) CHARACTER SET utf8mb4,
  `VoteID` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VoteLink` (
  `VoteName` VARCHAR(100) CHARACTER SET utf8mb4,
  `VoteLink` VARCHAR(100) CHARACTER SET utf8mb4,
  `VoteImg` VARCHAR(100) CHARACTER SET utf8mb4,
  `VoteDate` VARCHAR(100) CHARACTER SET utf8mb4,
  `VoteID` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `VoteSettingTime` (
  `VoteHour` INT,
  `VoteCategory` VARCHAR(50) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Web` (
  `webtitle` VARCHAR(100) CHARACTER SET utf8mb4,
  `resetmoney` VARCHAR(100) CHARACTER SET utf8mb4,
  `pkmoney` VARCHAR(100) CHARACTER SET utf8mb4,
  `resetlevel` VARCHAR(100) CHARACTER SET utf8mb4,
  `servername` VARCHAR(100) CHARACTER SET utf8mb4,
  `client` VARCHAR(100) CHARACTER SET utf8mb4,
  `patch` VARCHAR(100) CHARACTER SET utf8mb4,
  `launcher` VARCHAR(100) CHARACTER SET utf8mb4,
  `serverwebsite` VARCHAR(100) CHARACTER SET utf8mb4,
  `resetpoints` VARCHAR(100) CHARACTER SET utf8mb4,
  `resetslimit` VARCHAR(100) CHARACTER SET utf8mb4,
  `resetmode` VARCHAR(100) CHARACTER SET utf8mb4,
  `levelupmode` VARCHAR(100) CHARACTER SET utf8mb4,
  `announcements` LONGTEXT,
  `forum` VARCHAR(100) CHARACTER SET utf8mb4,
  `ads` LONGTEXT,
  `clean_inventory` VARCHAR(100) CHARACTER SET utf8mb4,
  `clean_skills` VARCHAR(100) CHARACTER SET utf8mb4,
  `store_inbox` VARCHAR(100) CHARACTER SET utf8mb4,
  `store_sent` VARCHAR(100) CHARACTER SET utf8mb4,
  `msg_length` VARCHAR(100) CHARACTER SET utf8mb4,
  `md5` VARCHAR(50) CHARACTER SET utf8mb4,
  `show_gm` VARCHAR(100) CHARACTER SET utf8mb4,
  `template` VARCHAR(50) CHARACTER SET utf8mb4,
  `warp_zen` VARCHAR(50) CHARACTER SET utf8mb4,
  `music` VARCHAR(50) CHARACTER SET utf8mb4,
  `header` VARCHAR(50) CHARACTER SET utf8mb4,
  `reset_stat` VARCHAR(50) CHARACTER SET utf8mb4,
  `reset_skill` VARCHAR(50) CHARACTER SET utf8mb4,
  `reset_quest` VARCHAR(50) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Web_admin` (
  `username` VARCHAR(100) CHARACTER SET utf8mb4,
  `password` VARCHAR(100) CHARACTER SET utf8mb4,
  `securitycode` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Web_links` (
  `link_name` VARCHAR(100) CHARACTER SET utf8mb4,
  `link_address` LONGTEXT,
  `link_description` LONGTEXT,
  `link_id` VARCHAR(100) CHARACTER SET utf8mb4,
  `link_date` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Web_mail` (
  `to_character` VARCHAR(100) CHARACTER SET utf8mb4,
  `from_character` VARCHAR(100) CHARACTER SET utf8mb4,
  `accountid` VARCHAR(100) CHARACTER SET utf8mb4,
  `subject` VARCHAR(100) CHARACTER SET utf8mb4,
  `mail_msg` VARCHAR(1000) CHARACTER SET utf8mb4,
  `inbox` VARCHAR(100) CHARACTER SET utf8mb4,
  `sent` VARCHAR(100) CHARACTER SET utf8mb4,
  `read_msg` VARCHAR(100) CHARACTER SET utf8mb4,
  `date` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Web_mail_store` (
  `accountid` VARCHAR(100) CHARACTER SET utf8mb4,
  `store_inbox` VARCHAR(100) CHARACTER SET utf8mb4,
  `store_sent` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Web_news` (
  `news_id` INT NOT NULL AUTO_INCREMENT,
  `news_title` VARCHAR(100) CHARACTER SET utf8mb4,
  `news_autor` VARCHAR(100) CHARACTER SET utf8mb4,
  `news_category` VARCHAR(100) CHARACTER SET utf8mb4,
  `news_context` LONGTEXT,
  `news_date` VARCHAR(100) CHARACTER SET utf8mb4,
  PRIMARY KEY (`news_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Web_servers` (
  `name` VARCHAR(100) CHARACTER SET utf8mb4,
  `experience` VARCHAR(100) CHARACTER SET utf8mb4,
  `drops` VARCHAR(100) CHARACTER SET utf8mb4,
  `gsport` VARCHAR(100) CHARACTER SET utf8mb4,
  `ip` VARCHAR(100) CHARACTER SET utf8mb4,
  `display_order` VARCHAR(100) CHARACTER SET utf8mb4,
  `version` VARCHAR(100) CHARACTER SET utf8mb4,
  `type` VARCHAR(50) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

