USE RanShop;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `LogShopPurchase` (
  `PurNum` BIGINT NOT NULL AUTO_INCREMENT,
  `PurKey` VARCHAR(21) CHARACTER SET utf8mb4 NOT NULL,
  `PurFlag` INT,
  `PurDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PurNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ShopItemMap` (
  `ProductNum` INT NOT NULL AUTO_INCREMENT,
  `ItemMain` INT,
  `ItemSub` INT,
  `ItemName` VARCHAR(100) CHARACTER SET utf8mb4,
  `ItemMoney` INT NOT NULL,
  `ItemType` INT,
  `ItemComment` VARCHAR(300) CHARACTER SET utf8mb4,
  `Duration` VARCHAR(50) CHARACTER SET utf8mb4,
  `Category` INT,
  `ItemStock` INT NOT NULL,
  `ItemImage` VARCHAR(300) CHARACTER SET utf8mb4,
  `ItemList` VARCHAR(100) CHARACTER SET utf8mb4,
  PRIMARY KEY (`ProductNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ShopPurchase` (
  `PurKey` INT NOT NULL AUTO_INCREMENT,
  `UserUID` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `ProductNum` INT NOT NULL,
  `PurPrice` INT NOT NULL DEFAULT 0,
  `PurFlag` INT NOT NULL DEFAULT 0,
  `PurDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PurChgDate` DATETIME,
  KEY `idx_ai_PurKey` (`PurKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ShopPurFlag` (
  `PurFlag` INT NOT NULL,
  `PurFlagName` VARCHAR(20) CHARACTER SET utf8mb4,
  PRIMARY KEY (`PurFlag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

