USE RanLog;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `HackProgramList` (
  `HackProgramNum` INT NOT NULL,
  `HackProgramName` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  PRIMARY KEY (`HackProgramNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ItemList` (
  `ProductNum` INT NOT NULL,
  `ItemMain` INT NOT NULL,
  `ItemSub` INT NOT NULL,
  `ItemName` VARCHAR(100) CHARACTER SET utf8mb4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogAction` (
  `ActionNum` BIGINT NOT NULL AUTO_INCREMENT,
  `ChaNum` INT NOT NULL DEFAULT 0,
  `Type` INT NOT NULL DEFAULT 0,
  `TargetNum` INT NOT NULL DEFAULT 0,
  `TargetType` INT NOT NULL DEFAULT 0,
  `BrightPoint` INT NOT NULL DEFAULT 0,
  `LifePoint` INT NOT NULL DEFAULT 0,
  `ExpPoint` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `ActionMoney` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `ActionDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ActionNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogExchangeFlag` (
  `ExchangeFlag` INT NOT NULL,
  `ExchangeName` VARCHAR(50) CHARACTER SET utf8mb4,
  PRIMARY KEY (`ExchangeFlag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogHackProgram` (
  `HackNum` INT NOT NULL AUTO_INCREMENT,
  `UserNum` INT NOT NULL DEFAULT 0,
  `ChaNum` INT NOT NULL DEFAULT 0,
  `SGNum` INT NOT NULL DEFAULT 0,
  `SvrNum` INT NOT NULL DEFAULT 0,
  `HackProgramNum` INT NOT NULL DEFAULT 0,
  `HackDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `HackComment` VARCHAR(512) CHARACTER SET utf8mb4 NOT NULL DEFAULT '',
  PRIMARY KEY (`HackNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogItemExchange` (
  `ExchangeNum` BIGINT NOT NULL AUTO_INCREMENT,
  `NIDMain` INT DEFAULT 0,
  `NIDSub` INT DEFAULT 0,
  `SGNum` INT DEFAULT 0,
  `SvrNum` INT DEFAULT 0,
  `FldNum` INT DEFAULT 0,
  `MakeType` INT NOT NULL DEFAULT 0,
  `MakeNum` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `ItemAmount` INT NOT NULL DEFAULT 0,
  `ItemFromFlag` INT NOT NULL DEFAULT 0,
  `ItemFrom` INT NOT NULL DEFAULT 0,
  `ItemToFlag` INT NOT NULL DEFAULT 0,
  `ItemTo` INT NOT NULL DEFAULT 0,
  `ExchangeFlag` INT NOT NULL DEFAULT 0,
  `ExchangeDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Damage` INT NOT NULL DEFAULT 0,
  `Defense` INT NOT NULL DEFAULT 0,
  `Fire` INT NOT NULL DEFAULT 0,
  `Ice` INT NOT NULL DEFAULT 0,
  `Poison` INT NOT NULL DEFAULT 0,
  `Electric` INT NOT NULL DEFAULT 0,
  `Spirit` INT NOT NULL DEFAULT 0,
  `CostumeMID` INT NOT NULL DEFAULT 0,
  `CostumeSID` INT NOT NULL DEFAULT 0,
  `TradePrice` DECIMAL(19,4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ExchangeNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogItemMax` (
  `NIDMain` INT NOT NULL DEFAULT 0,
  `NIDSub` INT NOT NULL DEFAULT 0,
  `SGNum` INT NOT NULL DEFAULT 0,
  `SvrNum` INT NOT NULL DEFAULT 0,
  `FldNum` INT NOT NULL DEFAULT 0,
  `MakeType` INT NOT NULL DEFAULT 0,
  `MaxNum` DECIMAL(19,4) DEFAULT 0,
  PRIMARY KEY (`NIDMain`,`NIDSub`,`SGNum`,`SvrNum`,`FldNum`,`MakeType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogItemRandom` (
  `RandomNum` BIGINT NOT NULL AUTO_INCREMENT,
  `NIDMain` SMALLINT DEFAULT 0,
  `NIDSub` SMALLINT DEFAULT 0,
  `SGNum` TINYINT UNSIGNED DEFAULT 0,
  `SvrNum` TINYINT UNSIGNED DEFAULT 0,
  `FldNum` TINYINT UNSIGNED DEFAULT 0,
  `MakeType` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `MakeNum` DECIMAL(19,4) NOT NULL DEFAULT 0,
  `RandomType1` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `RandomValue1` SMALLINT NOT NULL DEFAULT 0,
  `RandomType2` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `RandomValue2` SMALLINT NOT NULL DEFAULT 0,
  `RandomType3` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `RandomValue3` SMALLINT NOT NULL DEFAULT 0,
  `RandomType4` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `RandomValue4` SMALLINT NOT NULL DEFAULT 0,
  `RandomDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RandomNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogMakeType` (
  `MakeType` INT NOT NULL,
  `MakeName` VARCHAR(20) CHARACTER SET utf8mb4,
  PRIMARY KEY (`MakeType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogPetAction` (
  `ActionNum` BIGINT NOT NULL AUTO_INCREMENT,
  `PetNum` INT NOT NULL DEFAULT 0,
  `ItemMID` SMALLINT NOT NULL DEFAULT 0,
  `ItemSID` SMALLINT NOT NULL DEFAULT 0,
  `ActionType` SMALLINT NOT NULL DEFAULT 0,
  `PetFull` INT NOT NULL DEFAULT 0,
  `LogDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ActionNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogPetActionFlag` (
  `PetActionFlag` INT NOT NULL,
  `PetActionName` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`PetActionFlag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogServerState` (
  `SvrStateNum` INT NOT NULL AUTO_INCREMENT,
  `LogDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UserNum` INT NOT NULL DEFAULT 0,
  `UserMaxNum` INT NOT NULL DEFAULT 0,
  `SvrNum` INT NOT NULL DEFAULT 0,
  `SGNum` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`SvrStateNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogShopPurchase` (
  `PurNum` BIGINT NOT NULL AUTO_INCREMENT,
  `PurKey` VARCHAR(21) CHARACTER SET utf8mb4 NOT NULL,
  `PurFlag` INT,
  `PurDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PurNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogVehicleAction` (
  `ActionNum` BIGINT NOT NULL AUTO_INCREMENT,
  `VehicleNum` INT NOT NULL DEFAULT 0,
  `ItemMID` SMALLINT NOT NULL DEFAULT 0,
  `ItemSID` SMALLINT NOT NULL DEFAULT 0,
  `ActionType` SMALLINT NOT NULL DEFAULT 0,
  `VehicleBattery` INT NOT NULL DEFAULT 0,
  `LogDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ActionNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LogVehicleActionFlag` (
  `VehicleActionFlag` INT NOT NULL,
  `VehicleActionName` VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`VehicleActionFlag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ShopItemMap` (
  `ProductNum` INT NOT NULL,
  `ItemMain` INT,
  `ItemSub` INT,
  `ItemName` VARCHAR(100) CHARACTER SET utf8mb4,
  PRIMARY KEY (`ProductNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ShopPurchase` (
  `PurKey` VARCHAR(21) CHARACTER SET utf8mb4 NOT NULL,
  `UserUID` VARCHAR(6) CHARACTER SET utf8mb4 NOT NULL,
  `ProductNum` INT NOT NULL,
  `PurPrice` INT NOT NULL DEFAULT 0,
  `PurFlag` INT NOT NULL DEFAULT 0,
  `PurDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PurChgDate` DATETIME,
  PRIMARY KEY (`PurKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ShopPurFlag` (
  `PurFlag` INT NOT NULL,
  `PurFlagName` VARCHAR(20) CHARACTER SET utf8mb4,
  PRIMARY KEY (`PurFlag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SkillList` (
  `SkillMain` INT NOT NULL,
  `SkillSub` INT NOT NULL,
  `SkillName` VARCHAR(30) CHARACTER SET utf8mb4,
  `SkillGrade` INT,
  PRIMARY KEY (`SkillMain`,`SkillSub`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

